# Generated by Django 5.1.6 on 2025-12-31 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(verbose_name='recette')),
                ('spending', models.FloatField(verbose_name='depense')),
                ('solde', models.FloatField(verbose_name='solde')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(verbose_name='Prix Produit')),
                ('quantity', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Montant')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=20)),
                ('dateDebut', models.DateTimeField(auto_now=True)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('payedAmount', models.FloatField(verbose_name='Montant payé')),
                ('date', models.DateField(verbose_name='Date livre')),
                ('reduction', models.FloatField(verbose_name='Montant reduction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.client', verbose_name='Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.product', verbose_name='Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbProduct', models.IntegerField(verbose_name='Nombre de produit')),
                ('totalPrice', models.FloatField(verbose_name='Prix total')),
                ('totalPaid', models.FloatField(verbose_name='Total payé')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.FloatField(verbose_name='Total à payé')),
                ('PaidAmount', models.FloatField(verbose_name='Montant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.sale')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.stock', verbose_name='Stock'),
        ),
    ]
