# Generated by Django 5.2.9 on 2026-01-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(verbose_name='recette')),
                ('spending', models.FloatField(verbose_name='depense')),
                ('solde', models.FloatField(verbose_name='solde')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom complet')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('client_type', models.CharField(blank=True, choices=[('Particulier', 'particulier'), ('Grossiste', 'Grossiste'), ('Revendeur', 'Revendeur'), ('Entreprise', 'Entreprise')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(verbose_name='Prix Produit')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'DOLLARS'), ('CDF', 'FRANC')], max_length=5, null=True, verbose_name='Dévise')),
                ('quantity', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Montant')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=20, verbose_name='Nom du stock')),
                ('dateDebut', models.DateTimeField(auto_now=True)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('last_access_date', models.DateTimeField(auto_now=True)),
                ('last_access_product_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_credit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Money'), ('bank', 'Virement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trackshop.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbProduct', models.IntegerField(verbose_name='Nombre de produit')),
                ('totalPrice', models.FloatField(verbose_name='Prix total')),
                ('totalPaid', models.FloatField(verbose_name='Total payé')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.FloatField(verbose_name='Total à payé')),
                ('PaidAmount', models.FloatField(verbose_name='Montant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trackshop.sale')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trackshop.stock', verbose_name='Stock'),
        ),
    ]
