# Generated by Django 5.2.9 on 2026-01-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('eventory_type', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField()),
                ('physical_quantity', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackshop.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trackshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_returns', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackshop.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trackshop.saleitem')),
            ],
        ),
    ]
