# Generated by Django 5.2.9 on 2026-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='datet',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockName',
            field=models.CharField(max_length=20, verbose_name='Nom du stock'),
        ),
    ]
