# Generated by Django 5.2.9 on 2026-01-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='recette'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='solde',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='solde'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='spending',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='depense'),
        ),
        migrations.AlterField(
            model_name='clientdebt',
            name='PaidAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='clientdebt',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total à payé'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalPaid',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total payé'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix Produit'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trackshop.product'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
    ]
