# Generated by Django 5.2.9 on 2026-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0002_add_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10),
        ),
    ]
