# Generated by Django 5.2.9 on 2026-01-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0002_inventory_product_is_active_inventoryitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='eventory_type',
            new_name='inventory_type',
        ),
    ]
