# Generated by Django 5.2.9 on 2026-01-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0002_spending_datet_alter_client_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='datet',
            new_name='date',
        ),
    ]
