# Generated by Django 5.2.9 on 2026-01-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0003_alter_inventory_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('yearly', 'Annuel'), ('monthly', 'Mensuel')], max_length=10),
        ),
    ]
