# Generated by Django 5.2.9 on 2026-01-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0003_rename_datet_spending_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
    ]
