# Generated by Django 5.2.9 on 2026-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0003_alter_inventory_inventory_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbook',
            old_name='reference',
            new_name='reference_id',
        ),
        migrations.AddField(
            model_name='cashbook',
            name='reference_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10),
        ),
    ]
