# Generated by Django 5.2.9 on 2026-01-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0003_rename_dateadded_product_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
