# Generated by Django 5.2.9 on 2026-01-12 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0003_rename_eventory_type_inventory_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreturn',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='trackshop.saleitem'),
        ),
    ]
