# Generated by Django 5.2.9 on 2026-01-13 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0004_alter_productreturn_sale_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trackshop.inventory'),
        ),
        migrations.AlterField(
            model_name='inventorysummary',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='trackshop.inventory'),
        ),
    ]
