# Generated by Django 5.2.9 on 2026-01-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0004_purchaseitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
