# Generated by Django 5.2.9 on 2026-01-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0004_rename_reference_cashbook_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('yearly', 'Annuel'), ('monthly', 'Mensuel')], max_length=10),
        ),
    ]
