# Generated by Django 5.2.9 on 2026-01-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0004_rename_stock_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_access_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
