# Generated by Django 5.2.7 on 2026-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0005_alter_inventory_inventory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
