# Generated by Django 5.2.9 on 2026-01-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0005_stock_last_access_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trackshop.stock', verbose_name='Stock'),
        ),
    ]
