# Generated by Django 5.2.9 on 2026-01-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0005_alter_inventoryitem_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysummary',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='trackshop.inventory'),
        ),
    ]
