# Generated by Django 5.2.9 on 2026-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0006_alter_inventorysummary_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('yearly', 'Annuel'), ('monthly', 'Mensuel')], max_length=10),
        ),
    ]
