# Generated by Django 5.2.9 on 2026-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0006_purchase_is_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('yearly', 'Annuel'), ('monthly', 'Mensuel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
