# Generated by Django 5.2.9 on 2026-01-21 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0006_alter_inventory_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_access_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 21, 20, 21, 1, 712888, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
