# Generated by Django 5.2.9 on 2026-01-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_access_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
