# Generated by Django 5.2.9 on 2026-01-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0007_stock_last_access_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'DOLLARS'), ('CDF', 'FRANC')], max_length=5, null=True, verbose_name='Dévise'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='trackshop.product', verbose_name='Produit'),
        ),
    ]
