# Generated by Django 5.2.9 on 2026-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0007_alter_inventory_inventory_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
