# Generated by Django 5.2.9 on 2026-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0008_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
    ]
