# Generated by Django 5.2.9 on 2026-01-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0008_product_currency_alter_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='sale_date',
        ),
    ]
