# Generated by Django 5.2.9 on 2026-01-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0009_alter_inventory_inventory_type_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayment',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('yearly', 'Annuel'), ('monthly', 'Mensuel')], max_length=10),
        ),
    ]
