# Generated by Django 5.2.9 on 2026-01-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0010_alter_client_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post nom'),
        ),
    ]
