# Generated by Django 5.2.9 on 2026-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0011_alter_client_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='complete_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
