# Generated by Django 5.2.9 on 2026-01-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackshop', '0012_remove_client_lastname_remove_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Particulier', 'particulier'), ('Grossiste', 'Grossiste'), ('Revendeur', 'Revendeur'), ('Entreprise', 'Entreprise')], max_length=20, null=True),
        ),
    ]
