# Generated by Django 5.2.9 on 2026-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='id_nat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID.NAT'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rccm_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RCCM'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la boutique'),
        ),
    ]
